### ISSUE TITLE
Installation / Handling unclear

### ISSUE THREAD

**Issue by Christophwithlimitedclue** [mecrazy/stravaFollowers#1]
Hello @mecrazy,

I'd like to ask you to explain the installation process in a bit more detail, please.
My understanding of your install routine is: downloading one of the two files, creating a bookmark in the browser that links to the local storage and when having opened the Strava website, then to click onto the bookmark. If that's the intention, it does not work for me. Instead, the source code is displayed in the browser (Chrome) and I could not determine a setting that I needed to modify to allow for running the script.

Looking forward to your reply and best regards
Christoph

**Comment by mecrazy** [comment]
Hi @Christophwithlimitedclue,

The only file you need to download is ‘bookmarklet.js’.

Open it in Notepad (or your favourite text editor).

Select all the source text and copy it to the clipboard.

Paste it into the URL section and save it, as shown in the capture below.

You can then visit the Strava WEB site and click on this bookmark to run it.

![bookmarklet](https://github.com/user-attachments/assets/9a55b341-6196-43fe-bc0c-184bad6674ba)

**Comment by Christophwithlimitedclue** [comment]
Hello @mecrazy,

thanks a lot for the swift reply, it works like a gem now.

Kind regards
Christoph

**Comment by Christophwithlimitedclue** [comment]
Hello @mecrazy,

thanks a lot for the swift reply, it works like a gem now.

Kind regards
Christoph
